services:
  # web_app:
  #   build: 
  #     context: ./web_app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./web_app:/app
  #   depends_on:
  #     - calculator
  #   environment:
  #     - CALC_SERVICE_URL=http://calculator:5000

  calculator:
    build:
      context: ./calculator
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./calculator:/app
