services:
  calculator:
    build:
      context: ./calculator
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./calculator:/app
    
  web_app:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./web_app:/app
    depends_on:
      - calculator